name: InfraProvisioningPipeline
on: 
  repository_dispatch:
    types: [webhook]
run-name: Deploy to by @${{ toJSON(github.event.client_payload.name) }}

jobs:
  test:
    name: custom name
    runs-on: windows-latest
    env: 
      PAYLOAD: ${{toJSON(github.event.client_payload)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: hello
        run: echo "Hello World"
        shell: bash
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: node version
        run: node --version
      - name: run js file
        run: node index.js
      
      
      
