name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

env:
  Name: "Ravi"
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: "read file"
      #   env: 
      #     X: ${{2}}
      #   run: cat $GITHUB_WORKSPACE/plan-data/plan.json
      # - name: "read file from plan-data folder"
      #   run: |
      #     cd ./plan-data
          
      #     jq '.[] | .name' plan.json
      #     jq 'map(.name)' plan.json
      # - name: Greet
      #   id: greet
      #   uses: octocat/.github/action
      - name: folder
        run: |
          for dir in /forlderA/*/     # list directories in the form "/tmp/dirname/"
          do
              dir=${dir%*/}      # remove the trailing "/"
              echo "${dir##*/}"    # print everything after the final "/"
          done


         

          
          
          
          
